// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstart/fetchProfiles(request:)>
public struct FetchProfilesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The model to filter profiles by. Open-source models follow the
  /// Huggingface Hub `owner/model_name` format. If not provided, all models are
  /// returned. Use
  /// [GkeInferenceQuickstart.FetchModels][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]
  /// to find available models.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]: <doc:GkeInferenceQuickstart/fetchModels(request:)>
  public var model: Swift.String = Swift.String()

  /// Optional. The model server to filter profiles by. If not provided, all
  /// model servers are returned. Use
  /// [GkeInferenceQuickstart.FetchModelServers][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServers]
  /// to find available model servers for a given model.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServers]: <doc:GkeInferenceQuickstart/fetchModelServers(request:)>
  public var modelServer: Swift.String = Swift.String()

  /// Optional. The model server version to filter profiles by. If not provided,
  /// all model server versions are returned. Use
  /// [GkeInferenceQuickstart.FetchModelServerVersions][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServerVersions]
  /// to find available versions for a given model and server.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServerVersions]: <doc:GkeInferenceQuickstart/fetchModelServerVersions(request:)>
  public var modelServerVersion: Swift.String = Swift.String()

  /// Optional. The performance requirements to filter profiles. Profiles that do
  /// not meet these requirements are filtered out. If not provided, all profiles
  /// are returned.
  public var performanceRequirements: PerformanceRequirements? = nil

  /// Optional. The target number of results to return in a single response. If
  /// not specified, a default value will be chosen by the service. Note that the
  /// response may include a partial list and a caller should only rely on the
  /// response's
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]
  /// to determine if there are more instances left to be queried.
  ///
  /// [google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]: <doc:FetchProfilesResponse/nextPageToken>
  public var pageSize: Swift.Int32? = nil

  /// Optional. The value of
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]
  /// received from a previous `FetchProfilesRequest` call.
  /// Provide this to retrieve the subsequent page in a multi-page list of
  /// results. When paginating, all other parameters provided to
  /// `FetchProfilesRequest` must match the call that provided the page
  /// token.
  ///
  /// [google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]: <doc:FetchProfilesResponse/nextPageToken>
  public var pageToken: Swift.String? = nil

  /// Initialize a new instance of `FetchProfilesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchProfilesRequest().with { $0.model = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.FetchProfilesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
