// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [GkeInferenceQuickstart.FetchModelServerVersions][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServerVersions].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServerVersions]: <doc:GkeInferenceQuickstartClient/fetchModelServerVersions(request:options:)>
public struct FetchModelServerVersionsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The model for which to list model server versions. Open-source
  /// models follow the Huggingface Hub `owner/model_name` format. Use
  /// [GkeInferenceQuickstart.FetchModels][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]
  /// to find available models.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]: <doc:GkeInferenceQuickstartClient/fetchModels(request:options:)>
  public var model: Swift.String = Swift.String()

  /// Required. The model server for which to list versions. Open-source model
  /// servers use simplified, lowercase names (e.g., `vllm`). Use
  /// [GkeInferenceQuickstart.FetchModelServers][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServers]
  /// to find available model servers.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServers]: <doc:GkeInferenceQuickstartClient/fetchModelServers(request:options:)>
  public var modelServer: Swift.String = Swift.String()

  /// Optional. The target number of results to return in a single response.
  /// If not specified, a default value will be chosen by the service.
  /// Note that the response may include a partial list and a caller should
  /// only rely on the response's
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchModelServerVersionsResponse.next_page_token]
  /// to determine if there are more instances left to be queried.
  ///
  /// [google.cloud.gkerecommender.v1.FetchModelServerVersionsResponse.next_page_token]: <doc:FetchModelServerVersionsResponse/nextPageToken>
  public var pageSize: Swift.Int32? = nil

  /// Optional. The value of
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchModelServerVersionsResponse.next_page_token]
  /// received from a previous `FetchModelServerVersionsRequest` call.
  /// Provide this to retrieve the subsequent page in a multi-page list of
  /// results. When paginating, all other parameters provided to
  /// `FetchModelServerVersionsRequest` must match the call that provided the
  /// page token.
  ///
  /// [google.cloud.gkerecommender.v1.FetchModelServerVersionsResponse.next_page_token]: <doc:FetchModelServerVersionsResponse/nextPageToken>
  public var pageToken: Swift.String? = nil

  /// Initialize a new instance of `FetchModelServerVersionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchModelServerVersionsRequest().with { $0.model = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.FetchModelServerVersionsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
