// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:options:)>
public struct FetchProfilesResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// Output only. List of profiles that match the given model server info and
  /// performance requirements (if provided).
  public var profile: [Profile] = []

  /// Output only. The combined range of performance values observed across all
  /// profiles in this response.
  public var performanceRange: PerformanceRange? = nil

  /// Output only. Additional comments related to the response.
  public var comments: Swift.String = Swift.String()

  /// Output only. A token which may be sent as
  /// [page_token][FetchProfilesResponse.page_token] in a subsequent
  /// `FetchProfilesResponse` call to retrieve the next page of results. If this
  /// field is omitted or empty, then there are no more results to return.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `FetchProfilesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchProfilesResponse().with { $0.profile = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.FetchProfilesResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Profile] {
    return self.profile
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
