// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response message for
/// [GkeInferenceQuickstart.GenerateOptimizedManifest][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.GenerateOptimizedManifest].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.GenerateOptimizedManifest]: <doc:GkeInferenceQuickstartClient/generateOptimizedManifest(request:)>
public struct GenerateOptimizedManifestResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. A list of generated Kubernetes manifests.
  public var kubernetesManifests: [KubernetesManifest] = []

  /// Output only. Comments related to deploying the generated manifests.
  public var comments: [Swift.String] = []

  /// Output only. Additional information about the versioned dependencies used
  /// to generate the manifests. See [Run best practice inference with GKE
  /// Inference Quickstart
  /// recipes](https://cloud.google.com/kubernetes-engine/docs/how-to/machine-learning/inference/inference-quickstart)
  /// for details.
  public var manifestVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `GenerateOptimizedManifestResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateOptimizedManifestResponse().with { $0.kubernetesManifests = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.GenerateOptimizedManifestResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
