// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class GkeInferenceQuickstartLogging: GkeInferenceQuickstartStub {
    let inner: any GkeInferenceQuickstartStub
    let logger: Logger

    public init(_ inner: any GkeInferenceQuickstartStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-gkerecommender-v1"
      logger[metadataKey: "gcp.client.service"] = "gkerecommender"
      logger[metadataKey: "gcp.experimental.swift.client"] = "GkeInferenceQuickstart"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func fetchModels(
      request: FetchModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchModels",
        action: {
          (r: FetchModelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchModelsResponse
          in
          return try await self.inner.fetchModels(request: r, options: o)
        })
    }

    public func fetchModelServers(
      request: FetchModelServersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchModelServers",
        action: {
          (r: FetchModelServersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchModelServersResponse
          in
          return try await self.inner.fetchModelServers(request: r, options: o)
        })
    }

    public func fetchModelServerVersions(
      request: FetchModelServerVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchModelServerVersions",
        action: {
          (r: FetchModelServerVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse
          in
          return try await self.inner.fetchModelServerVersions(request: r, options: o)
        })
    }

    public func fetchProfiles(
      request: FetchProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchProfiles",
        action: {
          (r: FetchProfilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchProfilesResponse
          in
          return try await self.inner.fetchProfiles(request: r, options: o)
        })
    }

    public func generateOptimizedManifest(
      request: GenerateOptimizedManifestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateOptimizedManifest",
        action: {
          (r: GenerateOptimizedManifestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse
          in
          return try await self.inner.generateOptimizedManifest(request: r, options: o)
        })
    }

    public func fetchBenchmarkingData(
      request: FetchBenchmarkingDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchBenchmarkingData",
        action: {
          (r: FetchBenchmarkingDataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse
          in
          return try await self.inner.fetchBenchmarkingData(request: r, options: o)
        })
    }
  }
}
