// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol GkeInferenceQuickstartStub: Sendable {
    func fetchModels(
      request: FetchModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelsResponse

    func fetchModelServers(
      request: FetchModelServersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServersResponse

    func fetchModelServerVersions(
      request: FetchModelServerVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse

    func fetchProfiles(
      request: FetchProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse

    func generateOptimizedManifest(
      request: GenerateOptimizedManifestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse

    func fetchBenchmarkingData(
      request: FetchBenchmarkingDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse
  }
}
