// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Performance requirements for a profile and or model deployment.
public struct PerformanceRequirements: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The target Normalized Time Per Output Token (NTPOT) in
  /// milliseconds. NTPOT is calculated as `request_latency /
  /// total_output_tokens`. If not provided, this target will not be enforced.
  public var targetNtpotMilliseconds: Swift.Int32? = nil

  /// Optional. The target Time To First Token (TTFT) in milliseconds. TTFT is
  /// the time it takes to generate the first token for a request.  If not
  /// provided, this target will not be enforced.
  public var targetTtftMilliseconds: Swift.Int32? = nil

  /// Optional. The target cost for running a profile's model server. If not
  /// provided, this requirement will not be enforced.
  public var targetCost: Cost? = nil

  /// Initialize a new instance of `PerformanceRequirements`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PerformanceRequirements().with { $0.targetNtpotMilliseconds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.PerformanceRequirements"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
