// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Performance statistics for a model deployment.
public struct PerformanceStats: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The number of queries per second.
  /// Note: This metric can vary widely based on context length and may not be a
  /// reliable measure of LLM throughput.
  public var queriesPerSecond: Swift.Float = Swift.Float()

  /// Output only. The number of output tokens per second. This is the throughput
  /// measured as total_output_tokens_generated_by_server /
  /// elapsed_time_in_seconds.
  public var outputTokensPerSecond: Swift.Int32 = Swift.Int32()

  /// Output only. The Normalized Time Per Output Token (NTPOT) in milliseconds.
  /// This is the request latency normalized by the number of output tokens,
  /// measured as request_latency / total_output_tokens.
  public var ntpotMilliseconds: Swift.Int32 = Swift.Int32()

  /// Output only. The Time To First Token (TTFT) in milliseconds. This is the
  /// time it takes to generate the first token for a request.
  public var ttftMilliseconds: Swift.Int32 = Swift.Int32()

  /// Output only. The cost of running the model deployment.
  public var cost: [Cost] = []

  /// Initialize a new instance of `PerformanceStats`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PerformanceStats().with { $0.queriesPerSecond = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.PerformanceStats"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
