// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Performance range for a model deployment.
public struct PerformanceRange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The range of throughput in output tokens per second. This is
  /// measured as total_output_tokens_generated_by_server /
  /// elapsed_time_in_seconds.
  public var throughputOutputRange: TokensPerSecondRange? = nil

  /// Output only. The range of TTFT (Time To First Token) in milliseconds. TTFT
  /// is the time it takes to generate the first token for a request.
  public var ttftRange: MillisecondRange? = nil

  /// Output only. The range of NTPOT (Normalized Time Per Output Token) in
  /// milliseconds. NTPOT is the request latency normalized by the number of
  /// output tokens, measured as request_latency / total_output_tokens.
  public var ntpotRange: MillisecondRange? = nil

  /// Initialize a new instance of `PerformanceRange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PerformanceRange().with { $0.throughputOutputRange = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.PerformanceRange"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
