// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A profile containing information about a model deployment.
public struct Profile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The model server configuration. Use
  /// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]
  /// to find valid configurations.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:)>
  public var modelServerInfo: ModelServerInfo? = nil

  /// Output only. The accelerator type. Expected format: `nvidia-h100-80gb`.
  public var acceleratorType: Swift.String = Swift.String()

  /// Output only. The TPU topology (if applicable).
  public var tpuTopology: Swift.String = Swift.String()

  /// Output only. The instance type. Expected format: `a2-highgpu-1g`.
  public var instanceType: Swift.String = Swift.String()

  /// Output only. The resources used by the model deployment.
  public var resourcesUsed: ResourcesUsed? = nil

  /// Output only. The performance statistics for this profile.
  public var performanceStats: [PerformanceStats] = []

  /// Initialize a new instance of `Profile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Profile().with { $0.modelServerInfo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.Profile"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
